version: '3'
networks:
  default:

services:
  builder:
    build:
      context: ./
      dockerfile: Dockerfile.front
      target: builder
    container_name: build-sso
    networks:
      - default
    volumes:
      - ./front:/app/
    environment:
      REACT_APP_ENDPOINT: http://localhost:8081
