version: '3'
networks:
  default:

services:
  back:
    build: .
    tty: true
    restart: always
    networks:
      - default
    ports:
      - 8081:8080
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:8080 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./back/src:/home/api:ro

  rethink:
    image: rethinkdb:latest
    restart: always
    ports:
      - 8082:8080
    expose:
      - 28015
    volumes:
      - ./back/rethink/data:/data
    command: rethinkdb --bind all -d /data
    networks:
      - default
